import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';

export interface GenerateOptions {
  projectRoot: string;
  publisherKey: string;
  baseUrl: string;
  placementKey: string;
  placementName: string;
  size: 'responsive' | [number, number];
}

export interface GenerateResult {
  envFile: string;
  envAdded: boolean;
  libFile: string;
  libAdded: boolean;
  componentFile: string;
  componentAdded: boolean;
  gitignoreUpdated: boolean;
  /** Paths this CLI owns and therefore refreshed in place. */
  updated: string[];
  /** Paths that already existed without our marker and were left byte-for-byte alone. */
  preserved: string[];
}

const ENV_FILE = '.env.local';
const LIB_FILE = 'src/lib/clirevenue.js';
const COMPONENT_FILE = 'src/components/CLIRevenueAd.jsx';

/* The only two variables this CLI owns inside `.env.local`. Every other
   line in that file belongs to the user and is never touched. */
const ENV_OWNED_KEYS = ['VITE_CLIREVENUE_PUBLISHABLE_KEY', 'VITE_API_BASE_URL'];

/* A file carrying this header is one this CLI wrote, so re-running setup
   may refresh it. A file without it is the user's own work and is left
   exactly as found. This is what makes "re-run to change the placement"
   keep working without "setup overwrites my code" ever being true. */
const GENERATED_HEADER = '// Generated by `clirevenue setup`. Edits are overwritten on re-run.\n';

const LIB_CONTENT = `${GENERATED_HEADER}import { init } from '@clirevenue/sdk'

export const clirevenue = init(
  import.meta.env.VITE_CLIREVENUE_PUBLISHABLE_KEY,
  { baseUrl: import.meta.env.VITE_API_BASE_URL }
);
`;

const COMPONENT_CONTENT = (placementKey: string, size: 'responsive' | [number, number]) => {
  const layout = size === 'responsive' ? 'undefined' : `{ size: { width: ${size[0]}, height: ${size[1]} } }`;
  return `${GENERATED_HEADER}import { useEffect, useRef, useId } from 'react'
import { clirevenue } from '../lib/clirevenue'

function toLayout() {
  return ${layout};
}

export function CLIRevenueAd({ placementKey = '${placementKey}' }) {
  const ref = useRef(null)
  const id = useId()

  useEffect(() => {
    const el = ref.current
    if (!el) return

    let active = true
    const selector = '#' + id

    clirevenue.render(placementKey, selector, toLayout()).then(({ dispose }) => {
      if (!active) {
        dispose()
      } else {
        el._clirevenueDispose = dispose
      }
    }).catch(() => {})

    return () => {
      active = false
      if (el._clirevenueDispose) {
        el._clirevenueDispose()
        el._clirevenueDispose = null
      }
    }
  }, [placementKey, id])

  return <div id={id} ref={ref} className="clirevenue-ad-slot" />
}
`;
};

/**
 * Merges CLIRevenue's variables into an existing `.env.local`.
 *
 * This replaces the previous `writeFileSync(envPath, ENV_CONTENT(...))`,
 * which truncated the file and silently deleted every other variable the
 * project had. Now: absent file → created; existing file → only the two
 * owned keys are set (replaced in place, or appended if not already
 * present), every other line, comment and line ending survives.
 */
export function mergeEnvFile(
  existing: string | null,
  publisherKey: string,
  baseUrl: string,
): string {
  const values: Record<string, string> = {
    VITE_CLIREVENUE_PUBLISHABLE_KEY: publisherKey,
    VITE_API_BASE_URL: baseUrl,
  };

  if (existing === null) {
    return `${ENV_OWNED_KEYS.map((key) => `${key}=${values[key]}`).join('\n')}\n`;
  }

  /* Keep whatever line ending the user's file already uses rather than
     normalising it to LF behind their back. */
  const eol = existing.includes('\r\n') ? '\r\n' : '\n';

  const lines = existing.split(/\r?\n/);
  if (lines.length > 0 && lines[lines.length - 1] === '') {
    lines.pop();
  }

  const seen = new Set<string>();
  const merged = lines.map((line) => {
    const key = line.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/)?.[1];
    if (!key || !ENV_OWNED_KEYS.includes(key)) return line;
    seen.add(key);
    return `${key}=${values[key]}`;
  });

  for (const key of ENV_OWNED_KEYS) {
    if (!seen.has(key)) merged.push(`${key}=${values[key]}`);
  }

  return `${merged.join(eol)}${eol}`;
}

function ensureGitignore(projectRoot: string): boolean {
  const gitignorePath = join(projectRoot, '.gitignore');
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, '# Local env variables\n.env.local\n');
    return true;
  }

  const content = readFileSync(gitignorePath, 'utf8');
  if (content.includes('.env.local')) return false;

  const suffix = content.endsWith('\n') ? '' : '\n';
  writeFileSync(gitignorePath, content + suffix + '# Local env variables\n.env.local\n');
  return true;
}

/**
 * Writes one generated file, or refuses to touch a file it does not own.
 * Returns `'created'`, `'updated'` or `'preserved'`.
 */
function writeGeneratedFile(path: string, content: string): 'created' | 'updated' | 'preserved' {
  if (existsSync(path)) {
    let owned = false;
    try {
      owned = readFileSync(path, 'utf8').startsWith(GENERATED_HEADER);
    } catch {
      owned = false;
    }

    /* Not ours: leave it alone. Overwriting someone's own
       `src/lib/clirevenue.js` is exactly the kind of silent data loss
       this CLI must not do. */
    if (!owned) return 'preserved';

    writeFileSync(path, content);
    return 'updated';
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  return 'created';
}

export function generateIntegration(opts: GenerateOptions): GenerateResult {
  const envPath = join(opts.projectRoot, ENV_FILE);
  const libPath = join(opts.projectRoot, LIB_FILE);
  const componentPath = join(opts.projectRoot, COMPONENT_FILE);

  const updated: string[] = [];
  const preserved: string[] = [];

  const envAdded = !existsSync(envPath);
  mkdirSync(dirname(envPath), { recursive: true });
  writeFileSync(
    envPath,
    mergeEnvFile(envAdded ? null : readFileSync(envPath, 'utf8'), opts.publisherKey, opts.baseUrl),
  );

  const libOutcome = writeGeneratedFile(libPath, LIB_CONTENT);
  if (libOutcome === 'updated') {
    updated.push(libPath);
  } else if (libOutcome === 'preserved') {
    preserved.push(libPath);
  }

  const componentOutcome = writeGeneratedFile(
    componentPath,
    COMPONENT_CONTENT(opts.placementKey, opts.size),
  );
  if (componentOutcome === 'updated') {
    updated.push(componentPath);
  } else if (componentOutcome === 'preserved') {
    preserved.push(componentPath);
  }

  const gitignoreUpdated = ensureGitignore(opts.projectRoot);

  return {
    envFile: envPath,
    envAdded,
    libFile: libPath,
    libAdded: libOutcome === 'created',
    componentFile: componentPath,
    componentAdded: componentOutcome === 'created',
    gitignoreUpdated,
    updated,
    preserved,
  };
}