// Generated by `clirevenue setup`. Edits are overwritten on re-run.

import { useEffect, useId, useRef } from 'react';
import { renderPlacement } from '../lib/clirevenue.js';

const STYLE = { position: 'relative', minHeight: '1px' };

export function CLIRevenueAd({ placementKey, className }) {
  const id = useId();
  const ref = useRef(null);

  useEffect(() => {
    // useId() yields values like ":r0:" which CSS.escape() renders as
    // "\\:r0\\:", so the selector matches the element that actually exists.
    const selector = '#' + CSS.escape(id);
    const handle = renderPlacement(placementKey, selector);
    return () => handle?.dispose?.();
  }, [placementKey]);

  return <div id={id} ref={ref} className={className ?? 'clirevenue-ad-slot'} style={STYLE} />;
}

export default CLIRevenueAd;
